"""Added new column

Revision ID: b84e13c87f3b
Revises: 12cafd835bd9
Create Date: 2022-04-07 03:46:00.770775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84e13c87f3b'
down_revision = '12cafd835bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('appr', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'appr')
    # ### end Alembic commands ###
